working_directory = "C:/Users/cjr_1"

import = [
  # uncomment the flavour you want below:
  #"~/dot_files/alacritty/.config/alacritty/catppuccin-latte.toml"
  #"~/dot_files/alacritty/.config/alacritty/nord.toml"
  #"~/dot_files/alacritty/.config/alacritty/gruvbox_material_hard_dark.toml"
  "~/dot_files/alacritty/.config/alacritty/gruvbox_material_medium_dark.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"

  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "wsl.exe"
args = ["-e", "/bin/zsh"]

[window]
decorations = "none"
opacity = 0.96

[window.padding]
x = 10
y = 10

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

