customCommands:
  - key: "G"
    command: "gitmoji -c"
    context: "files"
    description: "Gitmoji Commit"
    subprocess: true
git:
  parseEmoji: true
gui:
  theme:
    activeBorderColor:
      - "#5E81AC"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#5E81AC"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
