alias ll="ls -al"

alias g="git"
alias gl="git log"
alias gb="git branch"
alias gs="git status"
alias ga="git add ."
alias gc="gitmoji -c"
alias gpo="git push origin"
alias gf="git fetch"
alias gco="git checkout"
alias gnb="git checkout -b"
alias gd="git branch -D"
